server:  #编码改成utf8后应该可以添加中文注释了
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.k1oud.dept.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
   application:
    name: springcloud-dept
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

  instance:
      instance-id: cloud-dept
      prefer-ip-address: true     #访问路径可以显示IP地址


info:
  app.name: springk1oud-dept
  company.name: www.k1oud.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

